version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 20
    commands:
      - yarn install
      - yarn global add netlify-cli@17.2.2

  build:
    commands:
      - netlify deploy --prod --build

post_build:
  commands:
    - netlify deploy --prod --build

artifacts:
  base-directory: out
  files:
    - "**/*"
